USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE EXERCISE_WH
WITH
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
SCALING_POLICY = "Economy"
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 3
INITIALLY_SUSPENDED = TRUE
COMMENT = "This is a virtual warehouse of size X-SMALL that can be used to process queries.";

DROP WAREHOUSE EXERCISE_WH;