USE ROLE SYSADMIN;

ALTER WAREHOUSE SECOND_WH RESUME;
ALTER WAREHOUSE SECOND_WH SUSPEND;

ALTER WAREHOUSE SECOND_WH SET WAREHOUSE_SIZE = XSMALL;
ALTER WAREHOUSE SECOND_WH SET AUTO_SUSPEND = 60;

DROP WAREHOUSE SECOND_WH;
